# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

    - name: Install Maven
      uses: yuzhiyongcn/setup-maven@v1.0.0            
      with:
        maven-version: 3.9.0
            
    - name: Install Xvfb
      run: sudo apt-get install xvfb
    
    - name: Print Maven Version
      run: xvfb-run --server-args="-screen 0, 1024x768x24" --auto-servernum mvn --version  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
    - name: Build with Maven
      run: xvfb-run --server-args="-screen 0, 1024x768x24" --auto-servernum mvn clean verify -Pother-os -Dtycho.localArtifacts=ignore -Dorg.eclipse.swtbot.search.timeout=20000 -Dscreenshots=${{ github.workspace }}/images  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
    - name: Upload Failed Tests screenshots
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Failed tests screenshots
        path: net.resheim.eclipse.timekeeper.test/screenshots

    - name: Upload screenshots
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Documentation screenshots
        path: images

    - name: Publish Surefire report
      uses: ScaCap/action-surefire-report@v1.0.13
      if: always()
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        report_paths: "**/target/surefire-reports/*.xml"

    - name: Create Version File
      run: (echo -n "VERSION=";mvn help:evaluate -Dexpression=project.version -q -DforceStdout) > version.txt

    - name: Create Version ENV Variable
      run: export $(< version.txt)                    
                    
    - name: Upload p2 repository Version: ${{ env.VERSION }}
      uses: actions/upload-artifact@v3
      with:
        name: Timekeeper${{ env.VERSION }}_build
        path: net.resheim.eclipse.timekeeper-site/target/repository
